[package]
name = "program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9.0"
borsh-derive = "0.9.0"
solana-program = "1.9.8"
common = { path = "../common" }
